name: Go

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: contract_published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.6'

    - name: List payload
      run: |
        'echo "pactUrl: ${{github.event.client_payload.pactUrl}} \n"'
        'echo "consumerName: ${{github.event.client_payload.consumerName}} \n"'
        'echo "providerName: ${{github.event.client_payload.providerName}} \n"'
        'echo "consumerVersionNumber: ${{github.event.client_payload.consumerVersionNumber}} \n"'
        'echo "providerVersionNumber: ${{github.event.client_payload.providerVersionNumber}} \n"'
        'echo "providerVersionTag: ${{github.event.client_payload.providerVersionTag}} \n"'
        'echo "consumerVersionTag: ${{github.event.client_payload.consumerVersionTag}} \n"'

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run build
      run: go build .

    - name: Run vet and lint
      run: |
        go vet .
        golint .

    - name: Run testing
      run: go test
